<?php

use App\Comuna;
use Illuminate\Database\Seeder;

class ComunaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Comuna::create(['comuna_id' => '1', 'name' => 'Iquique', 'region_id' => 1]);
        Comuna::create(['comuna_id' => '2', 'name' => 'Alto Hospicio', 'region_id' => 1]);
        Comuna::create(['comuna_id' => '3', 'name' => 'Pozo Almonte', 'region_id' => 1]);
        Comuna::create(['comuna_id' => '4', 'name' => 'Camiña', 'region_id' => 1]);
        Comuna::create(['comuna_id' => '5', 'name' => 'Colchane', 'region_id' => 1]);
        Comuna::create(['comuna_id' => '6', 'name' => 'Huara', 'region_id' => 1]);
        Comuna::create(['comuna_id' => '7', 'name' => 'Pica', 'region_id' => 1]);
        Comuna::create(['comuna_id' => '8', 'name' => 'Antofagasta', 'region_id' => 2]);
        Comuna::create(['comuna_id' => '9', 'name' => 'Mejillones', 'region_id' => 2]);
        Comuna::create(['comuna_id' => '10', 'name' => 'Sierra Gorda', 'region_id' => 2]);
        Comuna::create(['comuna_id' => '11', 'name' => 'Taltal', 'region_id' => 2]);
        Comuna::create(['comuna_id' => '12', 'name' => 'Calama', 'region_id' => 2]);
        Comuna::create(['comuna_id' => '13', 'name' => 'Ollagüe', 'region_id' => 2]);
        Comuna::create(['comuna_id' => '14', 'name' => 'San Pedro de Atacama', 'region_id' => 2]);
        Comuna::create(['comuna_id' => '15', 'name' => 'Tocopilla', 'region_id' => 2]);
        Comuna::create(['comuna_id' => '16', 'name' => 'María Elena', 'region_id' => 2]);
        Comuna::create(['comuna_id' => '17', 'name' => 'Chañaral', 'region_id' => 3]);
        Comuna::create(['comuna_id' => '18', 'name' => 'Diego de Almagro', 'region_id' => 3]);
        Comuna::create(['comuna_id' => '19', 'name' => 'Copiapó', 'region_id' => 3]);
        Comuna::create(['comuna_id' => '20', 'name' => 'Caldera', 'region_id' => 3]);
        Comuna::create(['comuna_id' => '21', 'name' => 'Tierra Amarilla', 'region_id' => 3]);
        Comuna::create(['comuna_id' => '22', 'name' => 'Vallenar', 'region_id' => 3]);
        Comuna::create(['comuna_id' => '23', 'name' => 'Alto del Carmen', 'region_id' => 3]);
        Comuna::create(['comuna_id' => '24', 'name' => 'Freirina', 'region_id' => 3]);
        Comuna::create(['comuna_id' => '25', 'name' => 'Huasco', 'region_id' => 3]);
        Comuna::create(['comuna_id' => '26', 'name' => 'Illapel', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '27', 'name' => 'Canela', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '28', 'name' => 'Los Vilos', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '29', 'name' => 'Salamanca', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '30', 'name' => 'Coquimbo', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '31', 'name' => 'Andacollo', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '32', 'name' => 'La Higuera', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '33', 'name' => 'La Serena', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '34', 'name' => 'Paihuano', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '35', 'name' => 'Vicuña', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '36', 'name' => 'Ovalle', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '37', 'name' => 'Combarbalá', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '38', 'name' => 'Monte Patria', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '39', 'name' => 'Punitaqui', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '40', 'name' => 'Río Hurtado', 'region_id' => 4]);
        Comuna::create(['comuna_id' => '41', 'name' => 'Isla de Pascua', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '42', 'name' => 'Los Andes', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '43', 'name' => 'Los Andes', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '44', 'name' => 'Rinconada', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '45', 'name' => 'San Esteban', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '46', 'name' => 'Quilpué', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '47', 'name' => 'Limache', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '48', 'name' => 'Olmué', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '49', 'name' => 'Villa Alemana', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '50', 'name' => 'La Ligua', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '51', 'name' => 'Cabildo', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '52', 'name' => 'Papudo', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '53', 'name' => 'Petorca', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '54', 'name' => 'Zapallar', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '55', 'name' => 'Quillota', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '56', 'name' => 'Hijuelas', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '57', 'name' => 'La Calera', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '58', 'name' => 'La Cruz', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '59', 'name' => 'Nogales', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '60', 'name' => 'San Antonio', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '61', 'name' => 'Algarrobo', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '62', 'name' => 'Cartagena', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '63', 'name' => 'El Quisco', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '64', 'name' => 'El Tabo', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '65', 'name' => 'Santo Domingo', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '66', 'name' => 'San Felipe', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '67', 'name' => 'Catemu', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '68', 'name' => 'Llay Llay', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '69', 'name' => 'Panquehue', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '70', 'name' => 'Putaendo', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '71', 'name' => 'Santa María', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '72', 'name' => 'Valparaíso', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '73', 'name' => 'Casablanca', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '74', 'name' => 'Concón', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '75', 'name' => 'Juan Fernández', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '76', 'name' => 'Puchuncaví', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '77', 'name' => 'Quintero', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '78', 'name' => 'Viña del Mar', 'region_id' => 5]);
        Comuna::create(['comuna_id' => '79', 'name' => 'Rancagua', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '80', 'name' => 'Codegua', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '81', 'name' => 'Coinco', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '82', 'name' => 'Coltauco', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '83', 'name' => 'Doñihue', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '84', 'name' => 'Graneros', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '85', 'name' => 'Las Cabras', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '86', 'name' => 'Machalí', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '87', 'name' => 'Malloa', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '88', 'name' => 'Mostazal', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '89', 'name' => 'Olivar', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '90', 'name' => 'Peumo', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '91', 'name' => 'Pichidegua', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '92', 'name' => 'Quinta de Tilcoco', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '93', 'name' => 'Rengo', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '94', 'name' => 'Requínoa', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '95', 'name' => 'San Vicente de Tagua Tagua', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '96', 'name' => 'Pichilemu', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '97', 'name' => 'La Estrella', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '98', 'name' => 'Litueche', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '99', 'name' => 'Marchigüe', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '100', 'name' => 'Navidad', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '101', 'name' => 'Paredones', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '102', 'name' => 'San Fernando', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '103', 'name' => 'Chépica', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '104', 'name' => 'Chimbarongo', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '105', 'name' => 'Lolol', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '106', 'name' => 'Nancagua', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '107', 'name' => 'Palmilla', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '108', 'name' => 'Peralillo', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '109', 'name' => 'Placilla', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '110', 'name' => 'Pumanque', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '111', 'name' => 'Santa Cruz', 'region_id' => 6]);
        Comuna::create(['comuna_id' => '112', 'name' => 'Cauquenes', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '113', 'name' => 'Chanco', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '114', 'name' => 'Pelluhue', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '115', 'name' => 'Curicó', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '116', 'name' => 'Hualañé', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '117', 'name' => 'Licantén', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '118', 'name' => 'Molina', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '119', 'name' => 'Rauco', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '120', 'name' => 'Romeral', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '121', 'name' => 'Sagrada Familia', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '122', 'name' => 'Teno', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '123', 'name' => 'Vichuquén', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '124', 'name' => 'Linares', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '125', 'name' => 'Colbún', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '126', 'name' => 'Longaví', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '127', 'name' => 'Parral', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '128', 'name' => 'Retiro', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '129', 'name' => 'San Javier', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '130', 'name' => 'Villa Alegre', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '131', 'name' => 'Yerbas Buenas', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '132', 'name' => 'Talca', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '133', 'name' => 'Constitución', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '134', 'name' => 'Curepto', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '135', 'name' => 'Empedrado', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '136', 'name' => 'Maule', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '137', 'name' => 'Pelarco', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '138', 'name' => 'Pencahue', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '139', 'name' => 'Río Claro', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '140', 'name' => 'San Clemente', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '141', 'name' => 'San Rafael', 'region_id' => 7]);
        Comuna::create(['comuna_id' => '142', 'name' => 'Lebu', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '143', 'name' => 'Arauco', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '144', 'name' => 'Cañete', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '145', 'name' => 'Contulmo', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '146', 'name' => 'Curanilahue', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '147', 'name' => 'Los Álamos', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '148', 'name' => 'Tirúa', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '149', 'name' => 'Los Ángeles', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '150', 'name' => 'Alto Bío Bío', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '151', 'name' => 'Antuco', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '152', 'name' => 'Cabrero', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '153', 'name' => 'Laja', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '154', 'name' => 'Mulchén', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '155', 'name' => 'Nacimiento', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '156', 'name' => 'Negrete', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '157', 'name' => 'Quilaco', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '158', 'name' => 'Quilleco', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '159', 'name' => 'San Rosendo', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '160', 'name' => 'Santa Bárbara', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '161', 'name' => 'Tucapel', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '162', 'name' => 'Yumbel', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '163', 'name' => 'Concepción', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '164', 'name' => 'Chiguayante', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '165', 'name' => 'Coronel', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '166', 'name' => 'Florida', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '167', 'name' => 'Hualpén', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '168', 'name' => 'Hualqui', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '169', 'name' => 'Lota', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '170', 'name' => 'Penco', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '171', 'name' => 'San Pedro de la Paz', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '172', 'name' => 'Santa Juana', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '173', 'name' => 'Talcahuano', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '174', 'name' => 'Tomé', 'region_id' => 8]);
        Comuna::create(['comuna_id' => '175', 'name' => 'Temuco', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '176', 'name' => 'Carahue', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '177', 'name' => 'Chol Chol', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '178', 'name' => 'Cunco', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '179', 'name' => 'Curarrehue', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '180', 'name' => 'Freire', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '181', 'name' => 'Galvarino', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '182', 'name' => 'Gorbea', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '183', 'name' => 'Lautaro', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '184', 'name' => 'Loncoche', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '185', 'name' => 'Melipeuco', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '186', 'name' => 'Nueva Imperial', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '187', 'name' => 'Padre Las Casas', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '188', 'name' => 'Perquenco', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '189', 'name' => 'Pitrufquén', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '190', 'name' => 'Pucón', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '191', 'name' => 'Saavedra', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '192', 'name' => 'Teodoro Schmidt', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '193', 'name' => 'Toltén', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '194', 'name' => 'Vilcún', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '195', 'name' => 'Villarrica', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '196', 'name' => 'Angol', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '197', 'name' => 'Collipulli', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '198', 'name' => 'Curacautín', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '199', 'name' => 'Ercilla', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '200', 'name' => 'Lonquimay', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '201', 'name' => 'Los Sauces', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '202', 'name' => 'Lumaco', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '203', 'name' => 'Purén', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '204', 'name' => 'Renaico', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '205', 'name' => 'Traiguén', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '206', 'name' => 'Victoria', 'region_id' => 9]);
        Comuna::create(['comuna_id' => '207', 'name' => 'Castro', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '208', 'name' => 'Ancud', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '209', 'name' => 'Chonchi', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '210', 'name' => 'Curaco de Vélez', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '211', 'name' => 'Dalcahue', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '212', 'name' => 'Puqueldón', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '213', 'name' => 'Queilén', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '214', 'name' => 'Quellón', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '215', 'name' => 'Quemchi', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '216', 'name' => 'Quinchao', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '217', 'name' => 'Puerto Montt', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '218', 'name' => 'Calbuco', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '219', 'name' => 'Cochamó', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '220', 'name' => 'Fresia', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '221', 'name' => 'Frutillar', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '222', 'name' => 'Los Muermos', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '223', 'name' => 'Llanquihue', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '224', 'name' => 'Maullín', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '225', 'name' => 'Puerto Varas', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '226', 'name' => 'Osorno', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '227', 'name' => 'Puerto Octay', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '228', 'name' => 'Purranque', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '229', 'name' => 'Puyehue', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '230', 'name' => 'Río Negro', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '231', 'name' => 'San Juan de la Costa', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '232', 'name' => 'San Pablo', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '233', 'name' => 'Chaitén', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '234', 'name' => 'Futaleufú', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '235', 'name' => 'Hualaihué', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '236', 'name' => 'Palena', 'region_id' => 10]);
        Comuna::create(['comuna_id' => '237', 'name' => 'Aysén', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '238', 'name' => 'Cisnes', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '239', 'name' => 'Guaitecas', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '240', 'name' => 'Cochrane', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '241', 'name' => 'O’Higgins', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '242', 'name' => 'Tortel', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '243', 'name' => 'Coyhaique', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '244', 'name' => 'Lago Verde', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '245', 'name' => 'Chile Chico', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '246', 'name' => 'Río Ibáñez', 'region_id' => 11]);
        Comuna::create(['comuna_id' => '247', 'name' => 'Cabo de Hornos', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '248', 'name' => 'Antártica', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '249', 'name' => 'Punta Arenas', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '250', 'name' => 'Laguna Blanca', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '251', 'name' => 'Río Verde', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '252', 'name' => 'San Gregorio', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '253', 'name' => 'Porvenir', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '254', 'name' => 'Primavera', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '255', 'name' => 'Timaukel', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '256', 'name' => 'Puerto Natales', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '257', 'name' => 'Torres del Paine', 'region_id' => 12]);
        Comuna::create(['comuna_id' => '258', 'name' => 'Colina', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '259', 'name' => 'Lampa', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '260', 'name' => 'Til Til', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '261', 'name' => 'Puente Alto', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '262', 'name' => 'Pirque', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '263', 'name' => 'San José de Maipo', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '264', 'name' => 'San Bernardo', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '265', 'name' => 'Buin', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '266', 'name' => 'Calera de Tango', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '267', 'name' => 'Paine', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '268', 'name' => 'Melipilla', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '269', 'name' => 'Alhué', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '270', 'name' => 'Curacaví', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '271', 'name' => 'María Pinto', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '272', 'name' => 'San Pedro', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '273', 'name' => 'Santiago', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '274', 'name' => 'Cerrillos', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '275', 'name' => 'Cerro Navia', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '276', 'name' => 'Conchalí', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '277', 'name' => 'El Bosque', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '278', 'name' => 'Estación Central', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '279', 'name' => 'Huechuraba', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '280', 'name' => 'Independencia', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '281', 'name' => 'La Cisterna', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '282', 'name' => 'La Florida', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '283', 'name' => 'La Granja', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '284', 'name' => 'La Pintana', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '285', 'name' => 'La Reina', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '286', 'name' => 'Las Condes', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '287', 'name' => 'Lo Barnechea', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '288', 'name' => 'Lo Espejo', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '289', 'name' => 'Lo Prado', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '290', 'name' => 'Macul', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '291', 'name' => 'Maipú', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '292', 'name' => 'Ñuñoa', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '293', 'name' => 'Pedro Aguirre Cerda', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '294', 'name' => 'Peñalolén', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '295', 'name' => 'Peñalolén', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '296', 'name' => 'Pudahuel', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '297', 'name' => 'Quilicura', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '298', 'name' => 'Quinta Normal', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '299', 'name' => 'Recoleta', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '300', 'name' => 'Renca', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '301', 'name' => 'San Joaquín', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '302', 'name' => 'San Miguel', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '303', 'name' => 'San Ramón', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '304', 'name' => 'Vitacura', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '305', 'name' => 'Talagante', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '306', 'name' => 'El Monte', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '307', 'name' => 'Isla de Maipo', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '308', 'name' => 'Padre Hurtado', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '309', 'name' => 'Peñaflor', 'region_id' => 13]);
        Comuna::create(['comuna_id' => '310', 'name' => 'La Unión', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '311', 'name' => 'Futrono', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '312', 'name' => 'Lago Ranco', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '313', 'name' => 'Río Bueno', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '314', 'name' => 'Valdivia', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '315', 'name' => 'Corral', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '316', 'name' => 'Lanco', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '317', 'name' => 'Los Lagos', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '318', 'name' => 'Máfil', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '319', 'name' => 'Mariquina', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '320', 'name' => 'Paillaco', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '321', 'name' => 'Panguipulli', 'region_id' => 14]);
        Comuna::create(['comuna_id' => '322', 'name' => 'Arica', 'region_id' => 15]);
        Comuna::create(['comuna_id' => '323', 'name' => 'Camarones', 'region_id' => 15]);
        Comuna::create(['comuna_id' => '324', 'name' => 'Putre', 'region_id' => 15]);
        Comuna::create(['comuna_id' => '325', 'name' => 'General Lagos', 'region_id' => 15]);
        Comuna::create(['comuna_id' => '326', 'name' => 'Bulnes', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '327', 'name' => 'Chillán', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '328', 'name' => 'Chillán Viejo', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '329', 'name' => 'El Carmen', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '330', 'name' => 'Pemuco', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '331', 'name' => 'Pinto', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '332', 'name' => 'Quillón', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '333', 'name' => 'San Ignacio', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '334', 'name' => 'Yungay', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '335', 'name' => 'Quirihue', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '336', 'name' => 'Cobquecura', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '337', 'name' => 'Coelemu', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '338', 'name' => 'Ninhue', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '339', 'name' => 'Portezuelo', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '340', 'name' => 'Ránquil', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '341', 'name' => 'Trehuaco', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '342', 'name' => 'San Carlos', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '343', 'name' => 'Coihueco', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '344', 'name' => 'Ñiquén', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '345', 'name' => 'San Fabián', 'region_id' => 16]);
        Comuna::create(['comuna_id' => '346', 'name' => 'San Nicolás', 'region_id' => 16]);
    }
}

